### ISSUE TITLE
日本語と英語のindex.htmlを切り替えられるようにする

### ISSUE THREAD

**Issue by Y-Kawada-dx** [yoshi46/iniad-fake-homepage#1]
日本語と英語それぞれのページはリンクづけられているが、言語間のリンクがないため言語を切り替えられない。
index.htmlとindex_en.htmlに言語切り替えのボタン又はリンクを張り、切り替え可能にする。

**Comment by yoshi46** [comment]
大河内さん、本件宜しくお願い致します。

**Comment by MASATO-OKOCHI** [comment]
本件完了いたしました。（河田さんのご助力により）
