### ISSUE TITLE
コースの画面から、東洋大学ホームページの各コース説明へリンクする

### ISSUE THREAD

**Issue by Y-Kawada-dx** [yoshi46/iniad-fake-homepage#2]
現状、course.htmlには各コースの名前が書かれているのみで情報が十分ない。
東洋大学のホームページには情報連携学部の各コース説明ページがあり、ここにリンクを紐づけることで説明を充実する。

コース説明へのリンク :
https://www.toyo.ac.jp/academics/faculty/iniad/course/318706
https://www.toyo.ac.jp/academics/faculty/iniad/course/318709
https://www.toyo.ac.jp/academics/faculty/iniad/course/318711
https://www.toyo.ac.jp/academics/faculty/iniad/course/318712

**Comment by yoshi46** [comment]
酒井さん、本件宜しくお願い致します。

**Comment by ksakai060** [comment]
金曜日の朝まで時間下さい
出来るところまで対応して連絡しますね

**Comment by yoshi46** [comment]
承知いたしました。引き続き、宜しくお願い致します。

**Comment by ksakai060** [comment]
検証できてませんが変更してみました（replitでエラーになりまして。。。）
